import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const ENDPOINT = "https://open-api.affiliate.shopee.com.br/graphql";
const SUPABASE_URL = Deno.env.get("SUPABASE_URL") || "";
const SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || "";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST,OPTIONS"};
function json(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{...cors,"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}})}
function getUserId(req:Request){const a=req.headers.get("Authorization")||"";const t=a.startsWith("Bearer ")?a.slice(7):"";if(!t)return null;try{const p=JSON.parse(atob(t.split(".")[1].replace(/-/g,"+").replace(/_/g,"/")));return typeof p.sub==="string"?p.sub:null}catch{return null}}
async function sha256Hex(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,"0")).join("")}
async function callShopee(query:string){const appId=Deno.env.get("SHOPEE_APP_ID")||"";const secret=Deno.env.get("SHOPEE_APP_SECRET")||"";if(!appId||!secret)return{ok:false,status:503,data:{},error:"Credenciais da Shopee ainda não configuradas."};const body=JSON.stringify({query});const timestamp=Math.floor(Date.now()/1000).toString();const signature=await sha256Hex(appId+timestamp+body+secret);const r=await fetch(ENDPOINT,{method:"POST",headers:{"Content-Type":"application/json","Authorization":`SHA256 Credential=${appId}, Timestamp=${timestamp}, Signature=${signature}`},body});const data=await r.json().catch(()=>({}));return{ok:r.ok&&!data?.errors?.length,status:r.status,data,error:data?.errors?.[0]?.message||null}}
async function rest(path:string,options:RequestInit={}){return fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...options,headers:{apikey:SERVICE_ROLE_KEY,Authorization:`Bearer ${SERVICE_ROLE_KEY}`,"Content-Type":"application/json",...(options.headers||{})}})}
async function ensurePlatform(){const r=await rest("platforms?nome=eq.Shopee&select=id&limit=1");const rows=await r.json().catch(()=>[]);if(Array.isArray(rows)&&rows[0]?.id)return rows[0].id;const c=await rest("platforms",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({nome:"Shopee",tipo:"afiliado",ativo:true})});const x=await c.json().catch(()=>[]);return Array.isArray(x)?x[0]?.id:x?.id}
function buildQuery(keyword:string,limit:number){const safe=JSON.stringify(keyword).slice(1,-1);return `{ productOfferV2(keyword: "${safe}", listType: 0, sortType: 1, page: 1, limit: ${Math.min(limit,50)}) { nodes { itemId productName productLink offerLink imageUrl priceMin priceMax priceDiscountRate sales ratingStar commissionRate sellerCommissionRate shopeeCommissionRate commission shopId shopName shopType periodStartTime periodEndTime } pageInfo { page limit hasNextPage } } }`}
function tokens(v:string){const aliases:Record<string,string>={running:"tenis",shoes:"tenis",shoe:"tenis",sneaker:"tenis",sneakers:"tenis",professional:"profissional",full:"completo",complete:"completo",carbon:"carbono",plate:"placa",maratona:"corrida",run:"corrida",portable:"portatil",neck:"pescoco",shoulder:"ombro",massage:"massageador",massagem:"massageador",thermal:"termico",cup:"copo",garrafa:"garrafa"};const stop=new Set(["de","da","do","das","dos","para","com","sem","e","em","um","uma","o","a","os","as","no","na","nos","nas","por","original","novo","nova","kit","tipo","modelo","cor","cores","tamanho","tamanhos","adulto","adulta","infantil","feminino","masculino","produto","oferta"]);return v.toLowerCase().normalize("NFD").replace(/[\\u0300-\\u036f]/g,"").replace(/[^a-z0-9]+/g," ").trim().split(/\\s+/).filter(Boolean).map(t=>aliases[t]||t).filter(t=>!stop.has(t))}
function distinctiveTokens(v:string){return [...new Set(tokens(v).filter(t=>t.length>=5||/\\d/.test(t)))];}
function titleSimilarity(a:string,b:string){const A=new Set(tokens(a)),B=new Set(tokens(b));if(!A.size||!B.size)return 0;let common=0;for(const t of A)if(B.has(t))common++;const union=new Set([...A,...B]).size;return common/union;}
function sameProduct(a:any,b:any){
  if(a.itemId!=null&&b.product_external_id!=null&&String(a.itemId)===String(b.product_external_id))return true;
  const au=String(a.productLink||a.url_produto||"").trim(),bu=String(b.productLink||b.url_produto||"").trim();if(au&&bu&&au===bu)return true;
  const ai=String(a.imageUrl||a.imagem_url||"").trim(),bi=String(b.imageUrl||b.imagem_url||"").trim();if(ai&&bi&&ai===bi)return true;
  const an=String(a.productName||a.titulo||""),bn=String(b.productName||b.titulo||"");
  const A=distinctiveTokens(an),B=new Set(distinctiveTokens(bn));
  let distinctiveCommon=0;for(const t of A)if(B.has(t))distinctiveCommon++;
  const hasModel=A.some(t=>/\\d/.test(t))&&distinctiveCommon>=2;
  if(hasModel)return true;
  if(distinctiveCommon>=3)return true;
  const sim=titleSimilarity(an,bn);
  const ta=tokens(an),tb=tokens(bn),minLen=Math.min(ta.length,tb.length);
  return (minLen>=6&&sim>=0.62)||(minLen>=4&&sim>=0.72);
}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({ok:false,error:"Use POST."},405);const body=await req.json().catch(()=>({}));const auth=req.headers.get("Authorization")||"";const serviceRole=SERVICE_ROLE_KEY&&auth==="Bearer "+SERVICE_ROLE_KEY;const userId=serviceRole&&body?.user_id?String(body.user_id):getUserId(req);if(!userId)return json({ok:false,error:"Usuário não autenticado."},401);if(!SUPABASE_URL||!SERVICE_ROLE_KEY)return json({ok:false,error:"Configuração do Supabase incompleta."},500);const limit=Math.min(Math.max(Number(body.limit)||20,1),50);const diagnostics:any[]=[];let all:any[]=[];for(let page=1;page<=10;page++){const query=buildQuery("",50).replace("page: 1","page: "+page);const r=await callShopee(query);const nodes=r.data?.data?.productOfferV2?.nodes||[];diagnostics.push({tipo:"busca_geral",pagina:page,keyword:"(geral)",status:r.status,resultados:nodes.length,erro:r.error});all.push(...nodes);if(!r.ok||nodes.length<50||r.data?.data?.productOfferV2?.pageInfo?.hasNextPage===false)break}
const byId=new Map<string,any>();for(const p of all.filter((x:any)=>x?.itemId!=null)){const k=String(p.itemId);if(!byId.has(k))byId.set(k,p)}const ranked=[...byId.values()].map((p:any)=>{const sales=Math.max(Number(p.sales)||0,0),discount=Math.max(Math.min(Number(p.priceDiscountRate)||0,100),0),rating=Math.max(Number(p.ratingStar)||0,0);return {...p,_rankScore:Math.log10(sales+1)*18+discount*1.2+rating*2}}).sort((a:any,b:any)=>b._rankScore-a._rankScore);
const platformId=await ensurePlatform();if(!platformId)return json({ok:false,error:"Não foi possível localizar/cadastrar a plataforma Shopee."},500);const er=await rest(`offers?user_id=eq.${encodeURIComponent(userId)}&platform_id=eq.${encodeURIComponent(platformId)}&store_provider=eq.shopee&select=id,product_external_id,titulo,preco_atual,preco_anterior,comissao_estimada,score_oferta,url_produto,store_product_url,imagem_url&limit=5000`);const rows=await er.json().catch(()=>[]);const old=Array.isArray(rows)?rows:[];
const oldByExternalId=new Map(old.filter((x:any)=>x?.product_external_id!=null).map((x:any)=>[String(x.product_external_id),x]));
const freshCandidates=ranked.filter((p:any)=>!oldByExternalId.has(String(p.itemId)));
const selected:any[]=[];let similaresFiltrados=0;for(const p of freshCandidates){if(selected.some(x=>sameProduct(p,x))){similaresFiltrados++;continue}selected.push(p);if(selected.length>=limit)break}
const existingCandidates=ranked.filter((p:any)=>oldByExternalId.has(String(p.itemId)));
let novas=0,atualizadas=0,duplicatasEvitadas=0;const ofertas:any[]=[];for(const p of [...existingCandidates,...selected]){const productName=String(p.productName||"Produto Shopee"),price=Number(p.priceMin),discount=Number(p.priceDiscountRate);const current=Number.isFinite(price)&&price>0?price:null,discountPct=Number.isFinite(discount)&&discount>0?discount:0,original=current&&discountPct>0&&discountPct<100?Number((current/(1-discountPct/100)).toFixed(2)):null;const values:any={user_id:userId,platform_id:platformId,titulo:productName,product_external_id:String(p.itemId),url_produto:p.productLink||null,preco_atual:current,preco_anterior:original,desconto_percentual:discountPct,comissao_percentual:Number(p.commissionRate)||null,comissao_estimada:Number(p.commission)||null,moeda:"BRL",disponibilidade:true,classificacao:discountPct>=10?"interessante":"verificar",permitido_afiliado:true,permitido_divulgacao:true,imagem_url:p.imageUrl||null,dados_origem:{provider:"shopee",...p,ranking:{score:p._rankScore,sales:Number(p.sales)||0,discount:discountPct}},store_provider:"shopee",store_product_url:p.productLink||null,affiliate_url:p.offerLink||null,oferta_tipo:"produto",score_oferta:p._rankScore,coletada_em:new Date().toISOString(),atualizada_em:new Date().toISOString()};const dup=oldByExternalId.get(String(p.itemId))||old.find((x:any)=>sameProduct(p,x));if(dup){duplicatasEvitadas++;if(String(dup.product_external_id)===String(p.itemId)){await rest(`offers?id=eq.${encodeURIComponent(dup.id)}&user_id=eq.${encodeURIComponent(userId)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify(values)});atualizadas++;ofertas.push({id:dup.id,...values})}continue}const ir=await rest("offers",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify(values)});const inserted=await ir.json().catch(()=>[]);if(ir.ok){novas++;ofertas.push({id:Array.isArray(inserted)?inserted[0]?.id:inserted?.id,...values})}}
return json({ok:true,provider:"shopee",modo_busca:"geral_mais_vendidos_e_melhores_descontos",categorias_forcadas:false,produtos:byId.size,selecionados:selected.length,novas_ofertas:novas,atualizadas,duplicatas_evitadas:duplicatasEvitadas,similares_filtrados:similaresFiltrados,diagnostico:diagnostics,ofertas})});